# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: featureflags 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "featureflags"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Al Davidson"]
  s.date = "2015-09-01"
  s.description = "Simple implementation of the 'Feature Flags' pattern as a Ruby gem.\nAllows you to set defaults in a Hash of the form:\n\n  ```{ feature_name_1: true, feature_name_2: false, feature_with_variations: 'A' }```\n\nand override them with correspondingly-named environment variables. \nIn the example above, you could enable the feature 'feature_name_2' with the environment variable 'FEATURE_NAME_2'.\n\n"
  s.email = "apdavidson@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "featureflags.gemspec",
    "lib/featureflags.rb",
    "lib/featureflags/features.rb",
    "spec/featureflags_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/aldavidson/featureflags"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "Simple ENV-based implementation of Feature Flags"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<byebug>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<byebug>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.3.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<byebug>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.3.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

